- package-lock.json
- package.json
- src/App.js
- src/components/common/Button.jsx
- src/components/common/Form.jsx
- src/pages/AuthorPage/Login/Login.jsx
- src/pages/AuthorPage/SignUp/SignUp.jsx
> Style: 로그인 회원가입 페이지

- src/components/common/Button/Button.jsx
- src/components/common/Form.jsx
- src/pages/AuthorPage/Login/Login.jsx
- src/pages/AuthorPage/SignUp/SignUp.jsx
유효성 검사를 위한 기능을 react-hook-form을 활용해서 구현
> Feat : Form-Validation

- src/App.js
- src/components/Modal/Modal.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
> Style: 모달 디자인 작업 중

- src/App.js
- src/components/Comment/Comment.jsx
- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/StarRating/StarRating.jsx
- src/components/styles/Globalstyle.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
- src/pages/Splash/Splash.jsx
- src/pages/Welcome/Welcome.jsx
- src/routes/Routers.jsx
> Style: 폰트 컴포넌트수정 스플레쉬 연결

- src/pages/Chat/ChatList.jsx
- src/pages/Chat/ChatRoom.jsx
- src/routes/Routers.jsx
Feat: Router 수정, Chat Modal 연결
> Feat: Router 수정, Chat Modal 연결

- src/components/Comment/Comment.jsx
- src/pages/Post/DetailPost.jsx
> Fix: 댓글 버튼 수정

- src/App.js
- src/components/Feed/PostHome.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Profile/ProfileInformation.jsx
- src/components/common/Nav/Navigation.jsx
> Fix: Router 수정

- src/components/Post/PostItem/PostItem.jsx
- src/components/Profile/ProfileBtn.jsx
- src/routes/Routers.jsx
> 라우터, 스타일 수정

- src/components/Profile/ProfileForm/ProfileForm.jsx
- Style: 페이지에 따라 이미지 버튼 위치 달라지는 문제 해결
- Feat: intro 필드 폼에 연결
> Feat: intro 필드 폼에 연결, Style: 이미지 버튼 위치 수정

- src/components/Auth/SignUpForm.jsx
- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/common/Header/Header.jsx
- src/components/styles/Globalstyle.jsx
- src/pages/Post/MakePost.jsx
게시물 작성 시 사진과 내용을 API 통신으로 서버와 연결
> Feat : Post API 통신

- src/components/Auth/LoginForm.jsx
- src/components/Modal/RecommendCard.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/StarRating/StarRating.jsx
- src/components/Profile/ProfileForm/ProfileForm.jsx
- src/components/Profile/RecommendList.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
- src/pages/Profile/Profile.jsx
- src/pages/Profile/ProfileEdit/ProfileEdit.jsx
Feat: 맛집 추천 업로드 및 게시 상세보기 기능 추가
> Feat: 맛집 추천 업로드 및 게시 상세보기 기능 추가

- src/components/Post/PostItem/PostItem.jsx
> Feat: 게시물 API 통신 출력

- src/components/Modal/Modal.jsx
- src/components/Modal/RecommendCard.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Profile/RecommendList.jsx
> Feat: RecommendCard Modal 연결

- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Profile/ProfileBtn.jsx
- src/components/common/Header/Header.jsx
- src/pages/Post/MakePost.jsx
Fix: 게시물 없을 경우 버튼 비활성화 및 사진 제한 (용량 및 포맷 제한)
> Fix: 게시물 없을 경우 버튼 비활성화 및 사진 제한

- src/components/Modal/Alert.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Profile/ProfileInformation.jsx
- src/pages/Post/DetailPost.jsx
> Feat: DetailPost 게시글 추가

- src/components/Modal/Alert.jsx
- src/components/Post/PostList/PostList.jsx
- src/pages/Post/DetailPost.jsx
> Fix: GridList 이미지만 출력

- src/components/Modal/Modal.jsx
- src/components/Modal/RecommendCard.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Profile/RecommendList.jsx
Style: RecommendCard, RecommendList ellipsis 추가
> Style: RecommendCard, RecommendList ellipsis 추가

- src/components/Feed/PostHome.jsx
- src/components/Modal/Modal.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Profile/Profile.jsx
Fix: Modal background issue 해결
> Fix: Modal background issue 해결

- src/components/Feed/PostHome.jsx
- src/components/Modal/Modal.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/pages/Home/Home.jsx
- src/pages/Post/DetailPost.jsx
> Feat: Home피드에서 DetailPost 연결

- src/components/Auth/SignUpForm.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Profile/ProfileForm/ProfileForm.jsx
- src/components/Profile/RecommendList.jsx
- src/components/Search/SearchList.jsx
- src/pages/Post/MakeRecommend.jsx
> fix: 회원가입 코드 최적화

- src/pages/Post/DetailPost.jsx
> Fix: DetailPost Delete 기능 수정

- src/components/Modal/Modal.jsx
- src/components/Modal/RecommendCard.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/pages/Post/DetailPost.jsx
> Fix: DetailPost Modal 수정

- package-lock.json
- package.json
- src/components/Feed/PostHome.jsx
- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Search/SearchList.jsx
- src/pages/Home/Home.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakePost.jsx
> Fix: 사진 압축 및 프로필 간 이동 수정

- src/App.js
- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Profile/ProfileInformation.jsx
- src/pages/Home/Home.jsx
- src/pages/Loading/Loading.jsx
- src/pages/Post/DetailPost.jsx
> Feat: Loading 페이지 연결

- src/components/Comment/Comment.jsx
- src/components/Profile/ProfileForm/ProfileForm.jsx
- src/pages/Post/DetailPost.jsx
- Feat: 댓글 등록, 댓글 리스트 확인
- Refactor: 프로필 폼 에러 페이지 적용 취소
> Feat: 댓글, Refactor: 프로필 폼 에러 페이지 적용 취소

- src/components/Chat/ChatListItem.jsx
- src/components/Chat/SendMessage.jsx
- src/components/common/Nav/ChatNavigation.jsx
- src/pages/Chat/ChatRoom.jsx
> Feat: 채팅 전송 기능 추가

- src/components/Auth/LoginForm.jsx
- src/components/Comment/Comment.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Profile/ProfileEdit/ProfileEdit.jsx
- 댓글 여러개인 경우 잘리는 이슈 해결
- 댓글 달리는 시간 계산하는 함수 추가
- 댓글 개수 포스트에 표시
- 댓글 입력창에서 자기 프로필 사진 표시
- 로그인 실패 시 에러 페이지 적용 삭제
> Feat: 댓글 관련 이슈 수정, 리팩토링

- src/components/Modal/Modal.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/pages/Post/DetailPost.jsx
Feat: 게시글 수정
모달 형태로 게시글 수정을 진행
> Feat: 게시글 수정

- src/components/Comment/Comment.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/pages/Home/Home.jsx
- src/pages/Post/DetailPost.jsx
> Style: 게시글 수정 UI

- src/components/Post/PostList/PostList.jsx
- src/pages/FollowerList/FollowerList.jsx
- src/pages/Home/Home.jsx
- src/pages/Map/Map.jsx
- src/pages/Map/MapStyle.css
- src/pages/Post/DetailPost.jsx
Fix: 10개 제한 해제 및 지도 overlay 디자인 및 외부 지도 연결
> Fix: 10개 제한 해제 및 지도 overlay 디자인 및 외부 지도 연결

- src/components/Feed/PostHome.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/pages/Post/DetailPost.jsx
> Fix: 상대 게시글 좋아요

- src/components/Modal/Modal.jsx
- src/components/Modal/RecommendCard.jsx
- src/components/Post/PostEdit/RecommendEdit.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Post/StarRating/StarRating.jsx
- src/pages/Map/Map.jsx
- src/pages/Map/MapStyle.css
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakeRecommend.jsx
> Fix: 추천맛집 수정기능 추가

- src/components/Profile/RecommendList.jsx
- src/pages/Profile/Profile.jsx
Fix: 추천맛집 수정 후 카드 닫을 때 정보 업데이트
> Fix: 추천맛집 수정 후 카드 닫을 때 정보 업데이트

- src/components/Post/PostEdit/RecommendEdit.jsx
- src/components/Profile/RecommendList.jsx
- src/pages/Profile/Profile.jsx
> Hoffix: 추천맛집 수정 핫픽스

- src/components/Post/PostEdit/RecommendEdit.jsx
- src/pages/Post/MakeRecommend.jsx
Fix: Recommend border-bottom 수정
> Fix: Recommend border-bottom 수정

- src/components/Auth/SignUpForm.jsx
- src/components/Modal/Alert.jsx
- src/components/Modal/Modal.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostEdit/RecommendEdit.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
- src/pages/Profile/Profile.jsx
FIx: 게시글 수정 시 사진 수정 + 회원가입 비밀번호 확인 + UI디테일
> FIx: 게시글 수정 시 사진 수정 + 회원가입 비밀번호 확인 + UI디테일

- src/components/Modal/Alert.jsx
- src/components/Modal/Modal.jsx
> Feat: 게시글 신고 기능 추가

- src/components/Post/PostEdit/PostEdit.jsx
> Hotfix: 게시글 수정 오류 해결

- README.md
> Docs: ReadMe 코드 설명 추가

- public/index.html
- src/App.js
- src/components/Auth/LoginForm.jsx
- src/components/Auth/LoginFormStyle.jsx
- src/components/Auth/SignUpForm.jsx
- src/components/Auth/SignUpFormStyle.jsx
- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Post/ImgPrev/PostImgPrevStyle.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/ImgPrev/RecommendImgPrevStyle.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostEdit/PostEditStyle.jsx
- src/components/Post/PostEdit/RecommendEdit.jsx
- src/components/Post/PostEdit/RecommendEditStyle.jsx
- src/components/Post/StarRating/StarRating.jsx
- src/components/styles/Globalstyle.jsx
- src/pages/AuthorPage/Login/Login.jsx
- src/pages/AuthorPage/SignUp/SignUp.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
> Refactor: 시멘틱 태그

- public/index.html
- src/components/Auth/SignUpForm.jsx
- src/components/Feed/PostHome.jsx
- src/components/Post/PostEdit/RecommendEdit.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostItem/PostItemStyle.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Post/PostList/PostListStyle.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/DetailPostStyle.jsx
- src/pages/Post/MakeRecommend.jsx
Refactor: PostItem, PostList 구조 변경 및 추천 맛집 주소 검색기능 추가
> Refactor: PostItem, PostList 구조 변경 및 추천 맛집 주소 검색기능 추가

- src/api/follow.js
- src/api/post.js
- src/api/recommend.js
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Search/SearchList.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakeRecommend.jsx
- src/pages/Profile/Profile.jsx
- Refactor: api 분리
- Fix: address->selectedAddress로 변경
> Refactor: api 분리, Fix: address->selectedAddress로 변경

- src/components/Modal/Alert/Alert.jsx
- src/components/Modal/RecommendCard/RecommendCard.jsx
- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Profile/RecommendList/RecommendList.jsx
- src/components/Search/SearchList.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
> Refactor: 사진 압축 기능 수정

- package-lock.json
- package.json
- src/App.js
- src/atoms/modalAtom.js
- src/atoms/randomFoodAtom.js
- src/components/Comment/Comment.jsx
- src/components/Feed/PostHome.jsx
- src/components/Modal/Alert/Alert.jsx
- src/components/Modal/Modal/Modal.jsx
- src/components/Modal/RecommendCard/RecommendCard.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/common/Header/Header.jsx
- src/components/styles/Globalstyle.jsx
- src/index.js
- src/pages/Chat/ChatList.jsx
- src/pages/Chat/ChatRoom.jsx
- src/pages/Map/Map.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakeRecommend.jsx
- src/pages/Profile/Profile.jsx
- src/routes/Routers.jsx
Refactor: modalAtom 파일 생성 및 recoil로 상태 관리
> Refactor: modalAtom 파일 생성 및 recoil로 상태 관리

- package-lock.json
- package.json
- src/assets/images/chevron-left.svg
- src/assets/images/chevron-right.svg
- src/assets/images/stack.svg
- src/components/Post/ImgPrev/PostEditPrev.jsx
- src/components/Post/ImgPrev/PostEditPrevStyle.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostEdit/PostEditStyle.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Post/PostList/PostListStyle.jsx
- src/components/common/Carousels/Carousel.jsx
- src/components/common/Carousels/CarouselStyle.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
Feat: 사진 세 장 업로드 및 캐러셀 수정 그리드 부분 디자인
> Feat: 사진 세장 업로드 및 캐러셀 수정 그리드 부분 디자인

- src/atoms/cardShowAtom.js
- src/components/Comment/Comment.jsx
- src/components/Modal/Alert/Alert.jsx
- src/components/styles/Globalstyle.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Profile/Profile.jsx
Refactor: handleDeletePost에서 window.location.reload를 다른 방법으로 대체
> Refactor: handleDeletePost에서 window.location.reload를 다른 방법으로 대체

- src/api/post.js
- src/components/Comment/Comment.jsx
- src/components/Comment/CommentStyle.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostItem/PostItemStyle.jsx
- src/components/Post/PostList/PostList.jsx
- src/pages/Post/DetailPost.jsx
- 프로필페이지에서 무한스크롤 구현
- 더보기 버튼 태그 수정
- 좋아요, 댓글 수정중
> Feat: 무한스크롤 

- src/components/Post/ImgPrev/PostImgPrev.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/common/Carousels/Carousel.jsx
- src/pages/Post/DetailPost.jsx
- src/pages/Post/MakePost.jsx
Refactor: 사진 업로드 및 수정, 사진 순서 드래그 기능 추가 및 사진 클릭 시 상세 페이지로 이동
> Refactor: 사진 업로드 및 수정 사진 순서 드래그 기능 추가 및 사진 클릭 시 상세 페이지로 이동

- src/components/Modal/Alert/Alert.jsx
- src/components/Modal/Modal/Modal.jsx
- src/pages/Post/DetailPost.jsx
Fix: 카카오맵에서 뒤로가기 누르면 RecommendCard 안 닫히는 오류 해결
> Fix: 카카오맵에서 뒤로가기 누르면 RecommendCard 안 닫히는 오류 해결

- src/components/Modal/Modal/Modal.jsx
- src/components/Post/PostList/PostList.jsx
> Refactor: 프로필에서 수정 기능 제거

- public/index.html
- src/components/Auth/LoginForm.jsx
- src/components/Modal/Modal/Modal.jsx
- src/components/Modal/RecommendCard/RecommendCard.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostEdit/PostEditStyle.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/Post/PostList/PostListStyle.jsx
- src/components/common/Carousels/Carousel.jsx
- src/components/common/Carousels/CarouselStyle.jsx
- src/components/common/Nav/NavigationStyle.jsx
Refactor: SNS 공유 및 사진 수정 기능 디자인 및 버그 수정
> Refactor: SNS 공유 및 사진 수정 기능 디자인 및 버그 수정

- package-lock.json
- package.json
- public/index.html
- src/components/Auth/LoginForm.jsx
- src/components/Feed/PostHome.jsx
- src/components/Post/PostItem/PostItem.jsx
- src/components/Post/PostList/PostList.jsx
- src/components/common/Carousels/CarouselStyle.jsx
- src/components/common/Header/Header.jsx
- src/components/common/Nav/Navigation.jsx
- src/components/common/Nav/NavigationStyle.jsx
- src/components/styles/Globalstyle.jsx
1. Top 버튼 고정 및 일정 스크롤 이상 내려야 보여지게 수정
2. Swal(SweetAlert2) 로그인 실패 시 alert 부분 디자인
3. 캐러셀 좌우 버튼 및 디자인 수정
> Refactor: Top 버튼 및 Swal 적용 etc.

- src/components/Auth/SignUpForm.jsx
- src/components/Feed/PostHome.jsx
- src/components/Modal/Alert/Alert.jsx
- src/components/Modal/Modal/Modal.jsx
- src/components/Post/ImgPrev/RecommendImgPrev.jsx
- src/components/Post/PostEdit/PostEdit.jsx
- src/components/Post/PostEdit/RecommendEditStyle.jsx
- src/components/Search/SearchList.jsx
- src/components/common/Carousels/Carousel.jsx
- src/components/common/Nav/NavigationStyle.jsx
- src/pages/Chat/ChatList.jsx
- src/pages/Chat/ChatRoom.jsx
- src/pages/Map/Map.jsx
- src/pages/Post/MakePost.jsx
- src/pages/Post/MakeRecommend.jsx
> Refactor: 주석 정리 및 코드 정리
